# Generated by Django 2.1.4 on 2019-06-13 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0002_auto_20190506_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
            bases=('Practicas.usuarios',),
        ),
        migrations.CreateModel(
            name='asignatura_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Alumno', verbose_name='alumno')),
            ],
            options={
                'verbose_name': 'Asignatura alumno',
                'verbose_name_plural': 'Asignaturas alumnos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura_inscrita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('seccion', models.CharField(max_length=50, verbose_name='sección')),
            ],
            options={
                'verbose_name': 'asignaturas inscritas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('duracionSemestres', models.IntegerField(verbose_name='duracion en semestres')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Centro_practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('horas_diarias', models.IntegerField(default=8, verbose_name='horas diarias de trabajo')),
            ],
            options={
                'verbose_name': 'centro de practica',
                'verbose_name_plural': 'centros de practica',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Practica_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_termino', models.DateField(verbose_name='fecha termino')),
                ('estado_practica', models.CharField(choices=[('Aceptada', 'Aceptada'), ('Anulada', 'Anulada'), ('Asignada', 'Asignada'), ('Reprobada', 'Reprobada'), ('Aprobada', 'Aprobada'), ('Enviada', 'Enviada')], default='Enviada', max_length=50, verbose_name='estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Alumno', verbose_name='alumno')),
                ('centro_practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Centro_practica', verbose_name='centro de practica')),
            ],
            options={
                'verbose_name': 'Practica_alumno',
                'verbose_name_plural': 'Practicas_alumno',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'profesores',
            },
            bases=('Practicas.usuarios',),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('telefono', models.IntegerField(verbose_name='teléfono')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Sede_Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Escuela', verbose_name='escuela')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Sede', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'Sede_escuela',
                'verbose_name_plural': 'Sedes_Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Supervisor_practica',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
            },
            bases=('Practicas.usuarios',),
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default='.', max_length=20, verbose_name='contraseña'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(default=11, max_length=100, verbose_name='correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(default=11, max_length=20, verbose_name='rut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Rol', verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('asignatura_inscrita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Asignatura_inscrita')),
                ('tipoPractica', models.CharField(choices=[('Profesional', 'Profesional'), ('Laboral', 'Laboral')], default='Laboral', max_length=20, verbose_name='tipo de practica')),
                ('cantidadHoras', models.IntegerField(verbose_name='cantidad de horas')),
            ],
            options={
                'verbose_name': 'Practica',
                'verbose_name_plural': 'Practicas',
            },
            bases=('Practicas.asignatura_inscrita',),
        ),
        migrations.AddField(
            model_name='centro_practica',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Supervisor_practica', verbose_name='supervisor'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='asignatura_inscrita',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='asignatura_alumno',
            name='asignatura_inscrita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Asignatura_inscrita', verbose_name='profesor'),
        ),
        migrations.AddField(
            model_name='practica_alumno',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Practica', verbose_name='Práctica'),
        ),
        migrations.AddField(
            model_name='practica',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Carrera', verbose_name='Carrera'),
        ),
    ]
