# Generated by Django 2.2 on 2019-05-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0002_auto_20190506_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios')),
                ('nota', models.IntegerField(verbose_name='nota')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=('Practicas.usuarios',),
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default='', max_length=20, verbose_name='contraseña'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(default='', max_length=20, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Practicas.Rol', verbose_name='rol'),
        ),
    ]
