# Generated by Django 2.2 on 2019-05-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0003_auto_20190527_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=20, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Rol', verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='rut'),
        ),
    ]
