# Generated by Django 2.2 on 2019-05-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0004_auto_20190527_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('duracionSemestres', models.IntegerField(verbose_name='duracion en semestres')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPractica', models.CharField(choices=[('Profesional', 'Profesional'), ('Laboral', 'Laboral')], default='Laboral', max_length=20, verbose_name='tipo de practica')),
                ('cantidadHoras', models.IntegerField(verbose_name='cantidad de horas')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Practica',
                'verbose_name_plural': 'Practicas',
            },
        ),
    ]
