# Generated by Django 2.2 on 2019-05-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0005_auto_20190527_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('telefono', models.IntegerField(verbose_name='teléfono')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.CreateModel(
            name='Sede_Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Carrera', verbose_name='Carrera')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Sede', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Sede_escuela',
                'verbose_name_plural': 'Sedes_Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Carrera_escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Carrera', verbose_name='Carrera')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Carrera_escuela',
                'verbose_name_plural': 'Carreras_Escuelas',
            },
        ),
    ]
