# Generated by Django 2.1.4 on 2019-06-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0006_auto_20190614_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='practica_alumno',
            name='estado_practica',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Anulada', 'Anulada'), ('Cerrada', 'Cerrada'), ('Inscrita', 'Inscrita')], default='Inscrita', max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='supervisor_practica',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
    ]
