# Generated by Django 2.2 on 2019-06-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0007_auto_20190527_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'centro de practica',
                'verbose_name_plural': 'centros de practica',
            },
        ),
        migrations.CreateModel(
            name='Supervisor_practica',
            fields=[
                ('usuarios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
            },
            bases=('Practicas.usuarios',),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.CreateModel(
            name='Practica_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha inicio')),
                ('fecha_termino', models.DateTimeField(verbose_name='fecha termino')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Alumno', verbose_name='alumno')),
                ('centro_practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Centro_practica', verbose_name='centro de practica')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Practica', verbose_name='Práctica')),
            ],
            options={
                'verbose_name': 'Practica_alumno',
                'verbose_name_plural': 'Practicas_alumno',
            },
        ),
        migrations.AddField(
            model_name='centro_practica',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practicas.Supervisor_practica', verbose_name='supervisor'),
        ),
    ]
