# Generated by Django 2.1.4 on 2019-06-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0008_auto_20190616_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura_alumno',
            name='nota1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AddField(
            model_name='asignatura_alumno',
            name='nota2',
            field=models.IntegerField(blank=True, null=True, verbose_name='nota 2'),
        ),
        migrations.AddField(
            model_name='asignatura_alumno',
            name='nota3',
            field=models.IntegerField(blank=True, null=True, verbose_name='nota 3'),
        ),
        migrations.AddField(
            model_name='asignatura_alumno',
            name='nota4',
            field=models.IntegerField(blank=True, null=True, verbose_name='nota 4'),
        ),
        migrations.AddField(
            model_name='asignatura_alumno',
            name='promedio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Promedio'),
        ),
        migrations.AddField(
            model_name='asignatura_inscrita',
            name='nota1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='supervisor_practica',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
    ]
