# Generated by Django 2.2 on 2019-06-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0010_auto_20190610_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_practica',
            name='horas_diarias',
            field=models.IntegerField(default=8, verbose_name='horas diarias de trabajo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='supervisor_practica',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
    ]
