# Generated by Django 2.2 on 2019-06-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practicas', '0011_auto_20190610_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica_alumno',
            name='estado_practica',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Anulada', 'Anulada'), ('Asignada', 'Asignada'), ('Reprobada', 'Reprobada'), ('Aprobada', 'Aprobada'), ('Enviada', 'Enviada')], default='Enviada', max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
        migrations.AlterField(
            model_name='supervisor_practica',
            name='usuarios_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Practicas.Usuarios'),
        ),
    ]
